name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy per SSH
    runs-on: ubuntu-latest
    steps:
      - name: Pull changes
        uses: appleboy/ssh-action@master
        with:
          script: git pull --rebase
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
