name: Deploy
on: [push]

jobs:
  deploy:
    # Job name is Greeting
    name: Deploy per SSH
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Pull changes
        uses: appleboy/ssh-action@master
        with:
          script: git pull --rebase
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
